// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-RQpUZcI2Xv6kUuhZWqJEF3Y0ZyBFoA',
    appId: '1:688078619727:web:5a7e2fa3c10b8deb3ed63a',
    messagingSenderId: '688078619727',
    projectId: 'flutter-day-47',
    authDomain: 'flutter-day-47.firebaseapp.com',
    storageBucket: 'flutter-day-47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWr0TzlCQRBPPq9HaS4OaOGvQD_BmGxi8',
    appId: '1:688078619727:android:b824e1230cf864fd3ed63a',
    messagingSenderId: '688078619727',
    projectId: 'flutter-day-47',
    storageBucket: 'flutter-day-47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDXKcAmEdSJ0hXwZRBObI2wZZTtffP0s',
    appId: '1:688078619727:ios:95c7e2506bf2ba7b3ed63a',
    messagingSenderId: '688078619727',
    projectId: 'flutter-day-47',
    storageBucket: 'flutter-day-47.appspot.com',
    iosBundleId: 'com.example.flutterDay47',
  );
}
